<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use App\Models\ClinicalRecordType;
use Illuminate\Support\Facades\DB;

class ClinicalRecordTypeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        $clinicalRecordTypes = [
            [
                'name' => 'Historia Clínica Estetica',
                'description' => '',
                'form_config' => '{}',
                'is_active' => true,
                'key_' => 'historiaEstetica',
            ],
            [
                'name' => 'Historia Clínica Facial',
                'description' => '',
                'form_config' => '{}',
                'is_active' => true,
                'key_' => 'historiaEsteticaFacial',
            ],
            [
                'name' => 'Historia Clínica Corporal',
                'description' => '',
                'form_config' => '{}',
                'is_active' => true,
                'key_' => 'historiaEsteticaCorporal',
            ],
            [
                'name' => 'Historia Estetica Laser',
                'description' => '',
                'form_config' => '{}',
                'is_active' => true,
                'key_' => 'historiaEsteticaLaser',
            ],
            [
                'name' => 'Historia Estetica Mesoterapia Capilar',
                'description' => '',
                'form_config' => '{}',
                'is_active' => true,
                'key_' => 'historiaEsteticaMesoterapiaCapilar',
            ],
            [
                'name' => 'Historia Estetica Mesoterapia Corporal',
                'description' => '',
                'form_config' => '{}',
                'is_active' => true,
                'key_' => 'historiaEsteticaMesoterapiaCorporal',
            ],
            [
                'name' => 'Historia Estetica Mesoterapia Facial',
                'description' => '',
                'form_config' => '{}',
                'is_active' => true,
                'key_' => 'historiaEsteticaMesoterapiaFacial',
            ],
            [
                'name' => 'Historia Clínica General',
                'description' => '',
                'form_config' => '{}',
                'is_active' => true,
                'key_' => 'general',
            ],
            [
                'name' => 'Historia Clínica Psicológica',
                'description' => '',
                'form_config' => '{}',
                'is_active' => true,
                'key_' => 'historiaPsicologia',
            ],
            [
                'name' => 'Control Diagnóstico Psicológía',
                'description' => '',
                'form_config' => '{}',
                'is_active' => true,
                'key_' => 'controlPsicologiaDiagnostico',
            ],
            [
                'name' => 'Control Psicológía Seguimiento',
                'description' => '',
                'form_config' => '{}',
                'is_active' => true,
                'key_' => 'controlPsicologiaSeguimiento',
            ],
            [
                'name' => 'Control Psicológía Grupal',
                'description' => '',
                'form_config' => '{}',
                'is_active' => true,
                'key_' => 'controlPsicologiaGrupal',
            ],
            [
                'name' => 'Historia Clínica Psicológica Infantil',
                'description' => '',
                'form_config' => '{}',
                'is_active' => true,
                'key_' => 'historiaPsicologiaInfantil',
            ],
            [
                'name' => 'Historia Clínica Psicológica Adultos',
                'description' => '',
                'form_config' => '{}',
                'is_active' => true,
                'key_' => 'historiaPsicologiaAdultos',
            ],
            [
                'name' => 'Historia Clínica Psicológica Adolescentes',
                'description' => '',
                'form_config' => '{}',
                'is_active' => true,
                'key_' => 'historiaPsicologiaAdolescentes',
            ],
            [
                'name' => 'Historia Clínica Psiquiátrica Inicial',
                'description' => '',
                'form_config' => '{}',
                'is_active' => true,
                'key_' => 'historiaPsiquiatria',
            ],
            [
                'name' => 'Historia Clínica de Seguimiento',
                'description' => '',
                'form_config' => '{}',
                'is_active' => true,
                'key_' => 'historiaPsiquiatriaSeguimiento',
            ],
            [
                'name' => 'Historia Clínica Pediátrica',
                'description' => '',
                'form_config' => '{}',
                'is_active' => true,
                'key_' => 'historiaPediatria',
            ],
            [
                'name' => 'Historia Nutricion',
                'description' => '',
                'form_config' => '{}',
                'is_active' => true,
                'key_' => 'historiaNutricion',
            ],
            [
                'name' => 'Historia Odontologia',
                'description' => '',
                'form_config' => '{}',
                'is_active' => true,
                'key_' => 'historiaOdontologia',
            ],
            [
                'name' => 'Historia Ortodoncia',
                'description' => '',
                'form_config' => '{}',
                'is_active' => true,
                'key_' => 'historiaOrtodoncia',
            ],
            [
                'name' => 'Historia Periodoncia',
                'description' => '',
                'form_config' => '{}',
                'is_active' => true,
                'key_' => 'historiaPeriodoncia',
            ],
            [
                'name' => 'Historia Endodoncia',
                'description' => '',
                'form_config' => '{}',
                'is_active' => true,
                'key_' => 'historiaEndodoncia',
            ],
            [
                'name' => 'Historia Otorrino',
                'description' => '',
                'form_config' => '{}',
                'is_active' => true,
                'key_' => 'historiaOtorrino',
            ],
            [
                'name' => 'historia Ginecologia',
                'description' => '',
                'form_config' => '{}',
                'is_active' => true,
                'key_' => 'historiaGinecologia',
            ],
            [
                'name' => 'control prenatal',
                'description' => '',
                'form_config' => '{}',
                'is_active' => true,
                'key_' => 'controlPrenatal',
            ],
            [
                'name' => 'Historia Urologia',
                'description' => '',
                'form_config' => '{}',
                'is_active' => true,
                'key_' => 'historiaUrologia',
            ],
            [
                'name' => 'Historia Traumatologia',
                'description' => '',
                'form_config' => '{}',
                'is_active' => true,
                'key_' => 'historiaTraumatologia',
            ],
            [
                'name' => 'Historia Cardiologia',
                'description' => '',
                'form_config' => '{}',
                'is_active' => true,
                'key_' => 'historiaCardiologia',
            ],
            [
                'name' => 'Historia Gastroenterologia',
                'description' => '',
                'form_config' => '{}',
                'is_active' => true,
                'key_' => 'historiaGastroenterologia',
            ],
            [
                'name' => 'Historia Oftalmología',
                'description' => '',
                'form_config' => '{}',
                'is_active' => true,
                'key_' => 'historiaOftalmologiaD',
            ],
            [
                'name' => 'Historia Optometría',
                'description' => '',
                'form_config' => '{}',
                'is_active' => true,
                'key_' => 'historiaOptometriaD',
            ],
            [
                'name' => 'Historia Diabetes',
                'description' => '',
                'form_config' => '{}',
                'is_active' => true,
                'key_' => 'historiaDiabetes',
            ],
            [
                'name' => 'Historia Endocrinología',
                'description' => '',
                'form_config' => '{}',
                'is_active' => true,
                'key_' => 'historiaEndocrinologia',
            ],
            [
                'name' => 'Historia epicrisis',
                'description' => '',
                'form_config' => '{}',
                'is_active' => true,
                'key_' => 'historiaEpicrisis',
            ],
            [
                'name' => 'Ecografia Obstétrica',
                'description' => '',
                'form_config' => '{}',
                'is_active' => true,
                'key_' => 'ecografiaObstetrica',
            ],
            [
                'name' => 'Ecografia Morfológica',
                'description' => '',
                'form_config' => '{}',
                'is_active' => true,
                'key_' => 'ecografiaMorfologica',
            ],
            [
                'name' => 'Ecografia Ultra Pélvica',
                'description' => '',
                'form_config' => '{}',
                'is_active' => true,
                'key_' => 'ecografiaUltrapelvica',
            ],
            [
                'name' => 'Colposcopia',
                'description' => '',
                'form_config' => '{}',
                'is_active' => true,
                'key_' => 'ecografiaColposcopia',
            ],
            [
                'name' => 'Renal',
                'description' => '',
                'form_config' => '{}',
                'is_active' => true,
                'key_' => 'ecografiaRenal',
            ],
            [
                'name' => 'Mamas',
                'description' => '',
                'form_config' => '{}',
                'is_active' => true,
                'key_' => 'ecografiaMamas',
            ],
            [
                'name' => 'Abdominal',
                'description' => '',
                'form_config' => '{}',
                'is_active' => true,
                'key_' => 'ecografiaAbdominal',
            ],
            [
                'name' => 'Historia Dermatología',
                'description' => '',
                'form_config' => '{}',
                'is_active' => true,
                'key_' => 'historiaDermatologia',
            ],
            [
                'name' => 'Historia Cirugía plástica',
                'description' => '',
                'form_config' => '{}',
                'is_active' => true,
                'key_' => 'historiaCirugiaPlastica',
            ],
            [
                'name' => 'Tratamiento Pestañas',
                'description' => '',
                'form_config' => '{}',
                'is_active' => true,
                'key_' => 'pestanasSPA',
            ],
            [
                'name' => 'Tratamiento Micropigmentación',
                'description' => '',
                'form_config' => '{}',
                'is_active' => true,
                'key_' => 'micropigmentacionSPA',
            ],
            [
                'name' => 'Tratamiento Remoción',
                'description' => '',
                'form_config' => '{}',
                'is_active' => true,
                'key_' => 'remocionSPA',
            ],
            [
                'name' => 'Informe quirúrgico',
                'description' => '',
                'form_config' => '{}',
                'is_active' => true,
                'key_' => 'informeQuirurgico',
            ],
            [
                'name' => 'Historia Oftalmología',
                'description' => '',
                'form_config' => '{}',
                'is_active' => true,
                'key_' => 'historiaOftalmologia',
            ],
            [
                'name' => 'Historia Visiometría',
                'description' => '',
                'form_config' => '{}',
                'is_active' => true,
                'key_' => 'historiaVisiometria',
            ],
            [
                'name' => 'Historia Optometría',
                'description' => '',
                'form_config' => '{}',
                'is_active' => true,
                'key_' => 'historiaOptometria',
            ],
            [
                'name' => 'Historia Podologia',
                'description' => '',
                'form_config' => '{}',
                'is_active' => true,
                'key_' => 'historiaPodologia',
            ],
            [
                'name' => 'Historia Fisioterapia',
                'description' => '',
                'form_config' => '{}',
                'is_active' => true,
                'key_' => 'historiaFisioterapia',
            ],
            [
                'name' => 'Historia Quiropráctica',
                'description' => '',
                'form_config' => '{}',
                'is_active' => true,
                'key_' => 'historiaQuiropractica',
            ],
            [
                'name' => 'Historia Pediatría',
                'description' => '',
                'form_config' => '{}',
                'is_active' => true,
                'key_' => 'historiaPediatriaA',
            ],
            [
                'name' => 'Historia Rehabilitación Cardiaca y Pulmonar',
                'description' => '',
                'form_config' => '{}',
                'is_active' => true,
                'key_' => 'historiaRehabilitacionCardiacaPulmonar',
            ],
            [
                'name' => 'Historia Fisioterapia',
                'description' => '',
                'form_config' => '{}',
                'is_active' => true,
                'key_' => 'historiaFisioterapiaA',
            ],
            [
                'name' => 'Historia Neumología',
                'description' => '',
                'form_config' => '{}',
                'is_active' => true,
                'key_' => 'historiaNeumologia',
            ],
        ];

        foreach ($clinicalRecordTypes as $recordType) {
            ClinicalRecordType::truncate();
            DB::table('clinical_record_types')->updateOrInsert([
                'name' => $recordType['name'],
                'description' => $recordType['description'],
                'form_config' => $recordType['form_config'],
                'is_active' => $recordType['is_active'],
                'key_' => $recordType['key_'],
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]);
        }
    }
}
